image: alpine

services:
  - docker:dind

stages:
  - build
  - deploy

cache:
    paths:
      - node_modules/

build:vuepress:
    stage: build
    image: node:lts
    script:
      - yarn install
      - yarn docs:build
    artifacts:
        paths:
          - dist
        expire_in: 1 day

deploy:staging:
    stage: deploy
    before_script:
      - apk add openssh-client
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY_STAGING" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - chmod 700 ~/.ssh
    script:
      - scp -r dist/* $SSH_HOST_STAGING:$SSH_PATH_STAGING
    only:
      - develop

deploy:prod:
  stage: deploy
  before_script:
    - apk add lftp
#    - eval $(ssh-agent -s)
#    - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -
#    - mkdir -p ~/.ssh
#    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#    - chmod 700 ~/.ssh
  script:
    - lftp -e "open $SSH_HOST_PROD; user $SSH_USERNAME_PROD $SSH_PASSWORD_PROD; mirror -X .* -X .*/ --reverse --verbose --delete dist/* lexique/; bye"
  only:
    - master