image: node:lts
pages:
    cache:
        paths:
            - node_modules/

    script:
        - yarn install
        - yarn docs:build
    artifacts:
        paths:
            - dist
    only:
        - master